### ISSUE TITLE
number of simulated points - multiple relaizations - bibliografy

### ISSUE THREAD

**Issue by aciniduva** [omitakahiro/Hawkes#2]
Hi,
I discovered today you're nice package for Hawkes process and I'm trying to use it. However, for my purposes, I need to simulate and estimate very long time series, e.g. with a baseline = 1 , branching ratio almost critical = 0.99 and simulation interval of order of 2e6 (or even grater if possible...). I founded that, on simulation interval smaller than the ones I'm interested in and in the case of power law kernel, you're ibrary performs better (in terms of simulationtime) than tick (https://x-datainitiative.github.io/tick/index.html). However, it seems that there's an upper bound on the number of points that can be simulated, 1e6 + 1 I would say. Is there any way to change it?
Moreover, I was wondering whther in both the simulation part and in the estimaiton part you used or not the approximation of the power law kernel introduced in https://link.springer.com/article/10.1140/epjb/e2013-40107-3 .
Finally, I wanted to ask whther is possible to simulate and fit multiple instances from the same system and which papers, more or less, you referred to in the library.
Thank you so much

**Comment by omitakahiro** [comment]
Hi

- You can change the maximum number of events in a single simulation by changing the value of `N_MAX` at line 118 in `/Hawkes/model.py` (https://github.com/omitakahiro/Hawkes/blob/master/Hawkes/model.py#L118).

- The intensity function of the model with a power-law kernel is calculated for simulation and inference using a technique introduced in  https://doi.org/10.1029/93GL02142.

- The implementation of multivariate Hawkes process is in progress, but it will take a while.

**Comment by aciniduva** [comment]
Thank you so much for your answer!
WIth respect to point 3, I was not asking for multivariate Hawkes but for multiple realizations of the same one dimensional Hawkes process, in such a way to simulate the maximization of the ensamble average of the likelihood function. In tick for example you can use the SimuHawkesMulti class (https://x-datainitiative.github.io/tick/modules/generated/tick.hawkes.SimuHawkesMulti.html) . 
Moreover, I'm facing som problema in the inference part as some times it takes very long time or seems not to converge. Is there a way to set some maximum number of iterations and/or some tolerance threshold? Or to plot the likelihood evaluated during the optimization?
Thank you in advance for your answers and however, you're tutorial is great!

**Comment by omitakahiro** [comment]
- In our package, parallel simulation of a Hawkes process is not implemented at this time.

- The likelihood and the norm of the gradient during the optimization is printed when you pass an optional argument to the `fit` function:
~~~python
h2.fit(T,itv,opt={'print':True})
~~~

- The maximum number of iterations can be also set similary: (In the below example, the optimization algorithm stops at the 10th step of the iterations)
~~~python
h2.fit(T,itv,opt={'print':True, 'stop':10})
~~~

- At the default setting, the optimization algorithm stops if the norm of the gradient become less than 1e-5. You can adjust this value at https://github.com/omitakahiro/Hawkes/blob/master/Hawkes/tools/Quasi_Newton.py#L135.
