### ISSUE TITLE
misc.ipynb is showing some errors while running ?

### ISSUE THREAD

**Issue by tonygracious** [omitakahiro/Hawkes#3]
ModuleNotFoundError: No module named 'Hawkes.BasisFunction'
So I change it to from Hawkes.tools.BasisFunction import loglinear_COS

then it showed
AttributeError: 'loglinear_COS' object has no attribute 'M_BF'

Then I change plot function to plt.plot(x,loglinear.A[:,i],lt[i])

Are these changes correct?

**Comment by omitakahiro** [comment]
This file was used just for creating figures for a tutorial of this library. Please just ignore this file.
